### ISSUE TITLE
Final Checkup Checklist

### ISSUE THREAD

**Issue by flaviogheri** [remla24-team-1/operations#18]
- [x] Test + Get Docker compose working on newer setup
- [x] Create new Data tests
- [x] Finish the Presentation !
- [x] Create the Overview Diagram for Kubernetes
- [x] update the Readmes for the various directories !
- [x] Merge the Vagrant branch !
- [x] Remove stale branches from github
- [x] Finish the Report !
        > finish ML Testing section
        > Look over the ML Pipeline 
        > Write future elaborations
- [x] Create a Demo Video !
- [x] Practice the Presentation
- [x] Explain what we've each done  in the project
- [x] Read over the Report
- [x] Submit report and Presentation !
- [x] Add Readme on .github/profile page
